In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
dataset = pd.read_csv('./cleanedDataset/cleanedDataset.csv' , index_col=False)
dataset.head()

                                        text sentiment
0       قرأت إن في مشروع تطوير جديد بمنطقتنا   neutral
1      بدي أغير روتيني شوي، حاسس محتاج تغيير   neutral
2   سمعت إن في مطعم جديد افتتح بشارع الرينبو   neutral
3  الشغل هاي الأيام ضغط ما بيوصف، كتير تعبان  negative
4       والله زهقت من ناس بتحكي وما بتعمل شي  negative

In [23]:
x = dataset['text']
y = dataset['sentiment']

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [28]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer

arabic_stopwords = [
    "من", "في", "على", "الى", "عن", "مع", "ان", "انها", "كان", "كانت", "هو", "هي", 
    "هذا", "هذه", "ذلك", "الذين", "التي", "كل", "قبل", "بعد", "كلما", "أو", "ام", "بل"
]

def normalize_arabic(text):
    if not isinstance(text, str):
        return ""
    text = re.sub(r"[\u064B-\u0652]", "", text) 
    text = re.sub(r"[أإآ]", "ا", text)          
    text = re.sub(r"ة", "ه", text)               
    text = re.sub(r"ي", "ى", text)               
    return text


x_train_clean = x_train.apply(normalize_arabic)
x_test_clean = x_test.apply(normalize_arabic)


vectorizer = TfidfVectorizer(
    stop_words=arabic_stopwords, 
    ngram_range=(1, 2),
    max_features=5000  
)

x_train_tfidf = vectorizer.fit_transform(x_train_clean)
x_test_tfidf = vectorizer.transform(x_test_clean)

### Linear Classifier

In [29]:
from sklearn.linear_model import LogisticRegression
linear_model = LogisticRegression(C=2.0, max_iter=1000, class_weight='balanced')
linear_model.fit(x_train_tfidf, y_train)

LogisticRegression(C=2.0, class_weight='balanced', max_iter=1000)

In [30]:
from sklearn.metrics import accuracy_score, classification_report
predictions = linear_model.predict(x_test_tfidf)

print(f"Accuracy: {accuracy_score(y_test, predictions) * 100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test, predictions))

Accuracy: 67.40%

Classification Report:
              precision    recall  f1-score   support

    negative       0.63      0.69      0.66       410
     neutral       0.67      0.67      0.67       586
    positive       0.72      0.67      0.69       455

    accuracy                           0.67      1451
   macro avg       0.68      0.67      0.67      1451
weighted avg       0.68      0.67      0.67      1451

In [31]:
def predict_sentiment_using_linear_model(new_text):
    text_vector = vectorizer.transform([new_text])
    prediction = linear_model.predict(text_vector)
    return prediction[0]

In [32]:
sample_review = "بكره محمد"
print(f"Review: '{sample_review}' -> Predicted Sentiment: {predict_sentiment_using_linear_model(sample_review)}")

Review: 'بكره محمد' -> Predicted Sentiment: neutral

### Non-Linear Classifier

In [33]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=500, random_state=42)
clf.fit(x_train_tfidf, y_train)

MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=500, random_state=42)

In [34]:
clf_predictions = clf.predict(x_test_tfidf)

print(f"Accuracy: {accuracy_score(y_test, clf_predictions) * 100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test, clf_predictions))

Accuracy: 62.30%

Classification Report:
              precision    recall  f1-score   support

    negative       0.59      0.63      0.61       410
     neutral       0.62      0.62      0.62       586
    positive       0.65      0.62      0.64       455

    accuracy                           0.62      1451
   macro avg       0.62      0.62      0.62      1451
weighted avg       0.62      0.62      0.62      1451

### Transformer

In [35]:
from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline


embedding_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

x_train_dense = embedding_model.encode(x_train.tolist(), show_progress_bar=True)
x_test_dense = embedding_model.encode(x_test.tolist(), show_progress_bar=True)

transformer_classifier = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=2000, C=1.0, class_weight='balanced')
)

transformer_classifier.fit(x_train_dense, y_train)

predictions = transformer_classifier.predict(x_test_dense)
print(f"Accuracy: {accuracy_score(y_test, predictions) * 100:.2f}%\n")
print(classification_report(y_test, predictions))

c:\Users\bilal\Desktop\pattern recognetion project\.venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\bilal\.cache\huggingface\hub\models--sentence-transformers--paraphrase-multilingual-MiniLM-L12-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 16267.77it/s]
Batches: 100%|██████████| 182/182 [00:23<00:00,  7.80it/s]
Batches: 100%|██████████| 46/46 [00:05<00:00,  7.88it/s]

Accuracy: 57.55%

              precision    recall  f1-score   support

    negative       0.52      0.62      0.57       410
     neutral       0.61      0.52      0.56       586
    positive       0.59      0.60      0.60       455

    accuracy                           0.58      1451
   macro avg       0.58      0.58      0.58      1451
weighted avg       0.58      0.58      0.58      1451

In [ ]:
import pandas as pd
import numpy as np
import torch
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import evaluate

label_dict = {'negative': 0, 'neutral': 1, 'positive': 2}
y_train_int = [label_dict[label] if isinstance(label, str) else label for label in y_train]
y_test_int = [label_dict[label] if isinstance(label, str) else label for label in y_test]

train_df = pd.DataFrame({'text': x_train, 'label': y_train_int})
test_df = pd.DataFrame({'text': x_test, 'label': y_test_int})


train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)


model_ckpt = "UBC-NLP/MARBERTv2"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

def tokenize_fn(batch):
    return tokenizer(batch['text'], truncation=True, padding='max_length', max_length=128)

tokenized_train = train_dataset.map(tokenize_fn, batched=True)
tokenized_test = test_dataset.map(tokenize_fn, batched=True)


model = AutoModelForSequenceClassification.from_pretrained(model_ckpt, num_labels=3)


metric = evaluate.load("accuracy")
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return metric.compute(predictions=preds, references=labels)


training_args = TrainingArguments(
    output_dir="./arabic_dialect_transformer",
    learning_rate=2e-5,             
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,              
    weight_decay=0.01,
    eval_strategy="epoch",           
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=torch.cuda.is_available(), 
    report_to="none"
)

# 7. Initialize Trainer using updated properties
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    processing_class=tokenizer,     
    compute_metrics=compute_metrics,
)

# 8. Run Training Loop
print("Starting MARBERTv2 Fine-Tuning Process...")
trainer.train()

# 9. Print Final Evaluation 
print("\nFinal Performance on Validation Set:")
print(trainer.evaluate())

c:\Users\bilal\Desktop\pattern recognetion project\.venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\bilal\.cache\huggingface\hub\models--UBC-NLP--MARBERTv2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Map: 100%|██████████| 5800/5800 [00:00<00:00, 17561.25 examples/s]
Map: 100%|██████████| 1451/1451 [00:00<00:00, 12634.65 examples/s]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 26187.26it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: UBC-NLP/MARBERTv2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting MARBERTv2 Fine-Tuning Process...

c:\Users\bilal\Desktop\pattern recognetion project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s]
c:\Users\bilal\Desktop\pattern recognetion project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.31it/s]
c:\Users\bilal\Desktop\pattern recognetion project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.12s/it]

Final Performance on Validation Set:

c:\Users\bilal\Desktop\pattern recognetion project\.venv\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.5457005500793457, 'eval_accuracy': 0.7842866988283942}

In [37]:
model.save_pretrained("./my_best_arabic_sentiment_model")
tokenizer.save_pretrained("./my_best_arabic_sentiment_model")

Writing model shards: 100%|██████████| 1/1 [00:08<00:00,  8.69s/it]

('./my_best_arabic_sentiment_model\\tokenizer_config.json',
 './my_best_arabic_sentiment_model\\tokenizer.json')